### ISSUE TITLE
Screenshots not working

### ISSUE THREAD

**Issue by senovsky** [QualityOps/wdio-timeline-reporter#20]
Hi, in the latest WebDriverIO v5.11.6 using [Cucumber-boilerplate](https://github.com/webdriverio/cucumber-boilerplate), the report is created correctly, but without screenshots. I'm getting the following error:

```
[chrome  windows nt #0-8] saveScreenshot expects a filepath of type string and ".png" file ending
[chrome  windows nt #0-8] Error: saveScreenshot expects a filepath of type string and ".png" file ending
[chrome  windows nt #0-8]     at Browser.saveScreenshot (C:\Users\something\e2e\node_modules\webdriverio\build\commands\browser\saveScreenshot.js:40:11)
[chrome  windows nt #0-8]     at Browser.runCommand (C:\Users\something\e2e\node_modules\@wdio\sync\build\wrapCommand.js:37:32)
[chrome  windows nt #0-8]     at Browser.runCommand (C:\Users\something\e2e\node_modules\@wdio\sync\build\wrapCommand.js:31:24)
[chrome  windows nt #0-8]     at Browser.<anonymous> (C:\Users\something\e2e\node_modules\@wdio\sync\build\wrapCommand.js:53:31)
[chrome  windows nt #0-8]     at World.saveScreenshot (C:\Users\something\e2e\steps/given.js:146:17)
[chrome  windows nt #0-8]     at Promise (C:\Users\something\e2e\node_modules\@wdio\sync\build\index.js:65:22)
[chrome  windows nt #0-8]     at World.executeSync (C:\Users\something\e2e\node_modules\@wdio\sync\build\index.js:63:10)
[chrome  windows nt #0-8]     at C:\Users\something\e2e\node_modules\@wdio\sync\build\runFnInFiberContext.js:21:27
```

Environment:
- OS version: Windows 10 Pro 1903 build 18362.207
- Browser version: Chrome 75.0.3770.142 64-bit
- Node.js version: 10.16.0 LTS
- NPM version: 6.9.0
- webdriver.io version: 5.11.10
- @wdio/cucumber-framework version: 5.11.10
- wdio-cucumberjs-json-reporter version: 1.0.6

**Comment by benzaremean** [comment]
Hi 
Could you provide details of the os? Sorry I haven't created an issues template

**Comment by senovsky** [comment]
Environment info added.

**Comment by benzaremean** [comment]
Thanks for the info I'm guessing the issue might be the file you saved was a jpeg. I'll have a look thanks. Alternatively you can try use a .png

I might be wrong

**Comment by benzaremean** [comment]
@senovsky the error is from webdriverio. will close this for now
