### ISSUE TITLE
TypeError: Cannot read property 'screenshots' of undefined in onAfterCommand

### ISSUE THREAD

**Issue by pako88** [QualityOps/wdio-timeline-reporter#37]
TypeError: Cannot read property 'screenshots' of undefined
    at TimelineReporter.onAfterCommand (/repo/node_modules/wdio-timeline-reporter/build/timeline-reporter.js:52:27)

![image](https://user-images.githubusercontent.com/28978631/69797139-7eb64b80-11cf-11ea-8a71-2ba59d1cf66f.png)

I'm running WDIO in sync mode with typescript. Do you need any additional informations?

**Comment by pako88** [comment]
problem was in before hooks. i'll created a PR

**Comment by benzaremean** [comment]
@pako88 you closed the issue? Does PR need to be merged?

**Comment by MacManus88** [comment]
I closed it to move discussion to PR.

Merge is still needed 

Thanks @benzaremean

**Comment by pako88** [comment]
I closed it to move discussion to PR.

Merge is still needed

Thanks @benzaremean
