### ISSUE TITLE
Screenshots are always created

### ISSUE THREAD

**Issue by Minja90** [QualityOps/wdio-timeline-reporter#39]
Timeline reporter has an issue with screenshots taking.

Even is specified that screenshots should be taken only on error, they are taken always.
So if I set  screenshotStrategy : 'on:error' , screenshots should be created only when error is present, but reporter even this is defined, taking screenshots. 

I noticed this using webdriver.io framework, version : v5

**Comment by jpamador** [comment]
I have the same issue mentioned here. It started when I added wdio-video-reporter before it was working fine, after I integrated that reporter I get a bunch of screenshots per test, no matter the screenshotStrategy I specify.

**Comment by jpamador** [comment]
I know what's the error at least in my case:
wdio-video-reporter uses screenshots to create the video (https://github.com/presidenten/wdio-video-reporter/blob/master/src/index.js#L100) and wdio-timeline-reporter is looking for any command that was executed that contains screenshot to be added to its journal (https://github.com/QualityOps/wdio-timeline-reporter/blob/master/lib/timeline-reporter.ts#L70). Timeline-reporter uses takeScreenshot, video-reporter uses saveScreenshot, if this validation were to be more specific (command.endpoint.includes('screenshot') &&) it would fix the issue between this 2 dependencies

**Comment by ajvj** [comment]
Adding the check for the screenshotStrategy as ` if (this.reporterOptions.screenshotStrategy!== 'none' && `  in https://github.com/QualityOps/wdio-timeline-reporter/blob/master/lib/timeline-reporter.ts#L72  will also help in this case.

**Comment by jpamador** [comment]
Hmm not completely as it would differentiate between in error and before click?

**Comment by ajvj** [comment]
When the video reporter is present, the need for screenshot on:error and before:click becomes redundant, so if the users want to have html report and video reporter together, they should have an option to disable taking screenshot, which would be met by setting the strategy as none.

**Comment by jpamador** [comment]
I agree that's a good compromise
