### ISSUE TITLE
Screenshots not embedded in report when downloaded from CI

### ISSUE THREAD

**Issue by vmwhereqa** [QualityOps/wdio-timeline-reporter#42]
<img width="1431" alt="Screen Shot 2020-06-18 at 3 34 32 PM" src="https://user-images.githubusercontent.com/63970843/85026683-41b8a300-b179-11ea-8a59-a176a3f0b3b1.png">

It is still referencing the build folder not the downloaded folder path.

**Comment by benzaremean** [comment]
this has been fixed in [PR41](https://github.com/QualityOps/wdio-timeline-reporter/pull/41)

**Comment by benzaremean** [comment]
Available in version 5.1.3
